---

roles:
#  - src: stefanhorning.virtualbox
  - src: ngetchell.vscode
  - src: geerlingguy.pip
  - src: geerlingguy.docker
  - src: pixelart.chrome
  - src: geerlingguy.nodejs

collections:
  - name: ansible.posix
