---

#http://docs.openhab.org/installation/linux.html#package-repository-installation

- name: install ppa key
  apt_key:
    url: "https://bintray.com/user/downloadSubjectPublicKey?username=openhab"
    state: present
  tags:
     - repo
     - openhab2

- name: install openhab2 repo
  apt_repository:
    repo: 'deb http://dl.bintray.com/openhab/apt-repo2 testing main'
    state: present
    update_cache: yes
    filename: openhab2
  tags:
     - repo
     - openhab2

- name: install openhab packages
  apt:
    pkg: "{{item}}"
    update_cache: yes
    cache_valid_time: 7200
  with_items:
    - openhab2
#     - openhab2-addons
#     - openhab2-addons-legacy
#     - sysstat
#     - nginx
#     - python-passlib
    - jq
    - curl
  tags:
     - packages
     - openhab2

- name: Add OpenHAB user to dialout group
  user:
    name: "{{openhab_user}}"
    groups: "dialout"
    append: yes
  tags:
    - openhab2
    - user

- name: Add ssh agent line to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: SSH_AUTH_SOCK
    line: Defaults env_keep += "SSH_AUTH_SOCK"

- name: Get auth socket
  command: echo $SSH_AUTH_SOCK
  changed_when: false
  register: ssh_auth_sock

- name: Enable access to SSH agent for openhab
  acl:
    path: "{{item.path}}"
    entity: "{{openhab_user}}"
    etype: user
    permissions: "{{item.permissions}}"
    state: present
  with_items:
    - path: "{{ ssh_auth_sock.stdout|dirname }}"
      permissions: x
    - path: "{{ ssh_auth_sock.stdout }}"
      permissions: rwx

# Get the config from Git
- stat:
    path: "{{openhab_config}}/.git"
  register: checkout_dir
  tags:
    - openhab
    - openhab-checkout

- name: Checkout OpenHAB config
  block:
    - name: Checkout OpenHAB config
      git:
        repo: "{{openhab_config_repo}}"
        dest: /tmp/openhab
        version: "{{openhab_config_version}}"
        force: yes
        accept_hostkey: yes
      become: yes
      become_user: "{{openhab_user}}"
      register: openhab-source-updated

    - name: Move old config
      command: mv {{openhab_config}} {{openhab_config}}.old
      become: true

    - name: Move new config
      command: mv /tmp/openhab {{openhab_config}}
      become: true

  when: false == checkout_dir.stat.exists
  tags:
    - openhab
    - openhab-checkout

- name: Update openhab
  git:
    repo: "{{openhab_config_repo}}"
    dest: "{{openhab_config}}"
    version: "{{openhab_config_version}}"
    accept_hostkey: yes
  register: openhab-source-updated
  become: "{{ ansible_user != openhab_user }}"
  become_user: "{{openhab_user}}"
  when: checkout_dir.stat.exists
  tags:
    - openhab
    - openhab-checkout

- name: "configure systemd"
  systemd:
    name: openhab2
    daemon_reload: yes
    enabled: true
    state: started
  tags:
    - openhab2
