---
- fatal:
    msg: TODO: Add Redhat install

#- name: Enable additional repositories
#  yum:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - http://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-14.ius.centos7.noarch.rpm
#    - epel-release
#  tags: php-cli-install
#
#- name: Install PHP 7.0
#  yum: name={{php_cli_php_rpm}}
#       state=latest
#  tags: php-cli-install
#
#- name: Install PHP 7.0 modules
#  yum: name={{php_cli_php_rpm}}-{{ item }}
#       state=latest
#  with_items: "{{ php_cli_php_modules }}"
#  tags: php-cli-install
#
#- name: Enable PHP in the command line
#  template:
#    src: enable_php.sh.j2
#    dest: /etc/profile.d/enable_{{php_cli_php_rpm}}.sh
#    mode: 0755
#  register: php_cli_enable
#
#- name: Enable PHP CLI now
#  command: /etc/profile.d/enable_{{php_cli_php_rpm}}.sh
#  when: php_cli_enable.changed
