---

# Cent OS 7 specific tasks
- name: upgrade all yum packages
  yum:
    name: '*'
    state: latest
    exclude: kernel*
  when: update is defined

- name: Install base packages
  yum:
    name: "{{ install_package }}"
    state: latest
  with_items:
    - libsemanage-python
  loop_control:
    loop_var: install_package


- name: Disable SE Linux
  selinux:
    state: "{{se_linux_state}}"
  when: se_linux_state is defined
