---
# Ubuntu specific tasks

- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags:
    - never
    - common-upgrade

- name: Install some common packages
  apt:
    name: "{{ common_packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400 #One day
  tags:
    - common
    - common-packages