---
# Ubuntu specific tasks

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day
  when: update is defined

- name: Install some common packages
  apt:
    name: "{{ package }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400 #One day
  with_items: "{{ common_packages }}"
  loop_control:
    loop_var: package
