---

- hosts: all
  gather_facts: no
  tasks:
    - include_tasks: tasks/bootstrap.yml

- hosts: all
  become: yes
  roles:
    - role: common

- hosts: all
  serial: 1
  tasks:
    - include_tasks: tasks/reboot_if_needed.yml
  tags: reboot
