---

- hosts: desktop
  gather_facts: no
  tasks:
    - include_tasks: tasks/bootstrap.yml

- hosts: desktop
  become: yes
  roles:
    - role: common
    - role: ngetchell.vscode
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: virtualbox
      virtualbox_php_install: no
      virtualbox_debian_release: focal
      virtualbox_version: 6.1
      virtualbox_extpack_version: 6.1.18
      virtualbox_user: "{{ ansible_user }}"
    - role: pixelart.chrome
  
  tasks:
    - name: Add PPAs
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - ppa:yubico/stable
        - ppa:kicad/kicad-5.1-releases
      tags: 
        - devbox
        - devbox-extra

    - name: Install aditional packages
      package:
        name:
          - fzf
          - terminator
          - yubikey-manager
          - pcscd
          - kicad
          - kicad-libraries
          - build-essential
          - php
          - clang
        state: present
      tags: 
        - devbox
        - devbox-extra

    - name: Make sure required services are started
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - pcscd
      tags: 
        - devbox
        - devbox-extra

    - name: Stop sleep after login
      lineinfile:
        path: /etc/systemd/logind.conf
        regex: "{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        HandleLidSwitch: "ignore"
        HandleLidSwitchDocked: "ignore"
      notify:
        - restart systemd-logind
      tags: 
        - devbox
        - devbox-config

    - name: Enable watching of large numbers of files
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: "524288"
        reload: yes
      tags: 
        - devbox
        - devbox-config

  handlers:
    - name: restart systemd-logind
      service:
        name: systemd-logind
        state: restarted

- hosts: desktop
  serial: 1
  tasks:
    - include_tasks: tasks/reboot_if_needed.yml
  tags: reboot
