---

- hosts: desktop
  gather_facts: no
  tasks:
    - include_tasks: tasks/bootstrap.yml

- hosts: desktop
  become: yes
  roles:
    - role: common
    - role: ngetchell.vscode
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: virtualbox
      virtualbox_php_install: no
      virtualbox_debian_release: focal
      virtualbox_version: 6.1
      virtualbox_extpack_version: 6.1.18
      virtualbox_user: "{{ ansible_user }}"
    - role: pixelart.chrome
    - role: geerlingguy.nodejs
      nodejs_version: "12.x"
      nodejs_npm_global_packages:
        - name: jslint
        - name: jest
        - name: eslint

  tasks:
    - name: Add repo keys
      apt_key:
        keyserver: "{{ item.keyserver }}"
        id: "{{ item.id }}"
        state: present
      with_items:
        - keyserver: keyserver.ubuntu.com
          id: C99B11DEB97541F0
      tags: 
        - devbox
        - devbox-extra

    - name: Add PPAs
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - ppa:yubico/stable
        - ppa:kicad/kicad-5.1-releases
        - deb https://cli.github.com/packages {{ ansible_distribution_release }} main
      tags: 
        - devbox
        - devbox-extra

    - name: Install aditional packages
      package:
        name:
          - curl
          - fzf
          - terminator
          - yubikey-manager
          - pcscd
          - kicad
          - kicad-libraries
          - build-essential
          - php
          - clang
          - ssh
          - jq
          - gh
        state: present
      tags: 
        - devbox
        - devbox-extra

    - name: Make sure required services are started
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - pcscd
        - docker
        - ssh
      tags: 
        - devbox
        - devbox-extra

    - name: Stop sleep after login
      lineinfile:
        path: /etc/systemd/logind.conf
        regex: "{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      with_dict:
        HandleLidSwitch: "ignore"
        HandleLidSwitchDocked: "ignore"
      notify:
        - restart systemd-logind
      tags: 
        - devbox
        - devbox-config

    - name: Enable watching of large numbers of files
      ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: "524288"
        reload: yes
      tags: 
        - devbox
        - devbox-config

    - name: Install Platform IO udev rules
      get_url:
        url: https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules
        dest: /etc/udev/rules.d/99-platformio-udev.rules
        mode: 0644
      notify:
        - restart udev
      tags: 
        - devbox
        - devbox-config

  handlers:
    - name: restart systemd-logind
      service:
        name: systemd-logind
        state: restarted

    - name: restart udev
      service:
        name: udev
        state: restarted

- hosts: desktop
  serial: 1
  tasks:
    - include_tasks: tasks/reboot_if_needed.yml
  tags: reboot
