---

- hosts: vm_servers
  gather_facts: no
  tasks:
    - include_tasks: tasks/bootstrap.yml

- hosts: vm_servers
  become: yes
  roles:
    - role: common

    - role: virtualbox

    - role: samba
      samba_log: /var/log/samba/log.%m
      samba_server_string: VM server
      samba_shares:
        - name: ISOs
          comment: ISO and VM images
          path: /home/{{ virtualbox_user }}/isos
          browseable: yes
          writable: yes
          guest_ok: no
          create_mode: "0666"
          directory_mode: "0770"
          owner: "{{ virtualbox_user }}"
          group: vboxusers
      samba_users:
        - name: "{{ virtualbox_user }}"
          password: "{{ virtualbox_user_pw|string }}"

- hosts: vm_servers
  serial: 1
  tasks:
    - include_tasks: tasks/reboot_if_needed.yml
  tags: reboot
