---

- hosts: vm_servers
  gather_facts: false
  tasks:
    - ansible.builtin.include_tasks: tasks/bootstrap.yml

- hosts: vm_servers
  become: true
  roles:
    - role: common

    - role: virtualbox
      virtualbox_version: latest
      virtualbox_extpack_version: auto
      virtualbox_php_install: false
      virtualbox_php_uninstall: true

    - role: samba
      samba_log: /var/log/samba/log.%m
      samba_server_string: VM server
      samba_shares:
        - name: ISOs
          comment: ISO and VM images
          path: /home/{{ virtualbox_user }}/isos
          browseable: true
          writable: true
          guest_ok: false
          create_mode: "0666"
          directory_mode: "0770"
          owner: "{{ virtualbox_user }}"
          group: vboxusers
      samba_users:
        - name: "{{ virtualbox_user }}"
          password: "{{ virtualbox_user_pw|string }}"

- hosts: vm_servers
  serial: 1
  tasks:
    - ansible.builtin.include_tasks: tasks/reboot_if_needed.yml
  tags: reboot
